FROM node:lts-alpine
WORKDIR /app
ARG PORT
ARG BACKEND_URL
ARG GOOGLE_CLIENT_ID
ENV ENV_PORT=$PORT
ENV NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
COPY . .
RUN npm install
RUN npm run build
CMD npm run start -- -p $ENV_PORT
EXPOSE $ENV_PORT