name: prod workflow

on:
  push:
    branches: [dev]

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build . -t octavianregatun/planitly-frontend:dev --build-arg PORT=3001 --build-arg BACKEND_URL="api" --build-arg GOOGLE_CLIENT_ID="609375541803-7gd5g5rs79tk1t1oup0rhv4t9j4n7h0s.apps.googleusercontent.com"

      - name: Docker push
        run: docker push octavianregatun/planitly-frontend:dev
